# Generated by Django 4.1.4 on 2023-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="basket",
            name="namber_of_item",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
