# Generated by Django 4.1.4 on 2023-01-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_category_options_alter_basket_namber_of_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="namber_of_item",
            new_name="number_of_item",
        ),
    ]
