# Generated by Django 4.1.4 on 2023-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default="Defautl something bla bla"),
            preserve_default=False,
        ),
    ]
