# Generated by Django 4.1.4 on 2023-01-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.discount",
            ),
        ),
    ]
