version: "3"

services:
  app:
    command: >
      sh -c "python shop/manage.py migrate &&
             python shop/manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/shop
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/app
    environment:
      - POSTGRES_DB=shop_tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  redis:
    image: redis:alpine
  
  celery:
    restart: always
    build: .
    command: >
        sh -c 
        "cd shop &&
        celery -A shop worker -l info"
    volumes:
      - .:/shop
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=shop_tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data: